export type Disease = {
  name: string;
  overview: string;
  symptoms: string[];
  preventions: string[];
  treatment: string[];
  whenToSeeDoctor: string[];
  riskFactors: string[];
};

export const DISEASES: Disease[] = [
  {
    name: "Diabetes",
    overview:
      "Diabetes is a chronic condition in which blood sugar (glucose) levels remain elevated due to the body's inability to produce or properly use insulin.",
    symptoms: ["Frequent urination", "Excessive thirst", "Unexplained weight loss", "Fatigue", "Blurred vision", "Slow-healing sores", "Tingling in hands or feet"],
    preventions: ["Maintain healthy weight", "Exercise regularly (30+ min/day)", "Eat a balanced, low-sugar diet", "Limit refined carbs and sugar", "Avoid tobacco", "Regular blood sugar screening"],
    treatment: ["Blood glucose monitoring", "Insulin therapy (Type 1)", "Oral medications (e.g., metformin)", "Diet and lifestyle management", "Regular A1C testing"],
    whenToSeeDoctor: ["Persistent high or low blood sugar", "Numbness in extremities", "Vision changes", "Unusual fatigue or thirst"],
    riskFactors: ["Family history", "Obesity", "Sedentary lifestyle", "Age over 45", "High blood pressure", "Gestational diabetes history"],
  },
  {
    name: "Heart Disease",
    overview:
      "Heart disease refers to several conditions affecting the heart, including coronary artery disease, arrhythmias, and heart defects.",
    symptoms: ["Chest pain or discomfort", "Shortness of breath", "Pain in neck, jaw, throat, upper abdomen or back", "Fatigue", "Irregular heartbeat", "Swelling in legs"],
    preventions: ["Don't smoke", "Eat heart-healthy diet", "Exercise 150 min/week", "Maintain healthy weight", "Manage stress", "Control cholesterol & blood pressure"],
    treatment: ["Lifestyle changes", "Medications (statins, beta-blockers)", "Angioplasty/stents", "Bypass surgery", "Cardiac rehabilitation"],
    whenToSeeDoctor: ["Chest pain", "Shortness of breath", "Fainting", "Rapid or irregular heartbeat"],
    riskFactors: ["High blood pressure", "High cholesterol", "Smoking", "Diabetes", "Obesity", "Family history", "Age"],
  },
  {
    name: "Asthma",
    overview:
      "Asthma is a chronic respiratory condition in which the airways narrow, swell and produce extra mucus, making breathing difficult.",
    symptoms: ["Shortness of breath", "Chest tightness", "Wheezing", "Coughing (especially at night)", "Trouble sleeping due to breathing"],
    preventions: ["Identify and avoid triggers", "Get vaccinated for flu and pneumonia", "Monitor breathing", "Take prescribed medications as directed"],
    treatment: ["Inhaled corticosteroids", "Quick-relief bronchodilators", "Long-acting beta agonists", "Allergy medications", "Biologic therapies"],
    whenToSeeDoctor: ["Worsening shortness of breath", "Rescue inhaler not helping", "Symptoms during minimal activity"],
    riskFactors: ["Family history", "Allergies", "Smoking", "Air pollution exposure", "Obesity"],
  },
  {
    name: "COVID-19",
    overview: "COVID-19 is an infectious respiratory disease caused by the SARS-CoV-2 coronavirus.",
    symptoms: ["Fever or chills", "Cough", "Shortness of breath", "Fatigue", "Loss of taste or smell", "Sore throat", "Headache", "Body aches"],
    preventions: ["Get vaccinated and boosted", "Wear masks in crowded settings", "Wash hands frequently", "Maintain physical distance when ill", "Ventilate indoor spaces"],
    treatment: ["Rest and hydration", "Over-the-counter symptom relief", "Antiviral medications (e.g., Paxlovid)", "Hospitalization for severe cases", "Oxygen therapy when needed"],
    whenToSeeDoctor: ["Trouble breathing", "Persistent chest pain", "Confusion", "Bluish lips or face", "High fever lasting >3 days"],
    riskFactors: ["Older age", "Underlying conditions", "Unvaccinated status", "Immunocompromised"],
  },
  {
    name: "Influenza (Flu)",
    overview: "Influenza is a contagious respiratory illness caused by influenza viruses that infect the nose, throat and lungs.",
    symptoms: ["Fever", "Chills", "Muscle aches", "Cough", "Congestion", "Runny nose", "Headaches", "Fatigue"],
    preventions: ["Annual flu vaccine", "Frequent handwashing", "Avoid close contact with sick people", "Cover coughs and sneezes"],
    treatment: ["Rest and fluids", "Antiviral drugs (oseltamivir)", "OTC pain relievers", "Decongestants"],
    whenToSeeDoctor: ["Difficulty breathing", "Persistent chest pain", "Severe weakness", "Symptoms that improve then worsen"],
    riskFactors: ["Age (very young or elderly)", "Weakened immune system", "Chronic illness", "Pregnancy"],
  },
  {
    name: "Thyroid Disorders",
    overview: "Thyroid disorders affect the thyroid gland's ability to produce hormones that regulate metabolism, energy, and growth.",
    symptoms: ["Weight changes", "Fatigue", "Hair loss", "Sensitivity to cold or heat", "Mood changes", "Irregular heartbeat"],
    preventions: ["Adequate iodine intake", "Avoid radiation exposure", "Don't smoke", "Regular check-ups if family history"],
    treatment: ["Hormone replacement (levothyroxine)", "Anti-thyroid medications", "Radioactive iodine", "Surgery in severe cases"],
    whenToSeeDoctor: ["Unexplained weight changes", "Persistent fatigue", "Neck swelling", "Heart palpitations"],
    riskFactors: ["Female gender", "Family history", "Autoimmune disease", "Age over 60", "Pregnancy"],
  },
  {
    name: "Stroke",
    overview: "A stroke occurs when blood supply to part of the brain is interrupted or reduced, depriving brain tissue of oxygen.",
    symptoms: ["Sudden numbness on one side", "Confusion", "Trouble speaking", "Vision problems", "Severe headache", "Loss of balance"],
    preventions: ["Control blood pressure", "Don't smoke", "Maintain healthy weight", "Exercise regularly", "Limit alcohol", "Treat heart conditions"],
    treatment: ["Clot-busting drugs (tPA)", "Mechanical thrombectomy", "Anticoagulants", "Rehabilitation therapy"],
    whenToSeeDoctor: ["Any FAST symptoms — Face drooping, Arm weakness, Speech difficulty — call emergency services immediately"],
    riskFactors: ["High blood pressure", "Diabetes", "Smoking", "High cholesterol", "Atrial fibrillation", "Age over 55"],
  },
  {
    name: "Cancer",
    overview: "Cancer is a broad group of diseases involving abnormal cell growth that can invade and spread to other parts of the body.",
    symptoms: ["Unexplained weight loss", "Persistent fatigue", "Lumps or thickening", "Skin changes", "Changes in bowel/bladder habits", "Persistent cough"],
    preventions: ["Don't use tobacco", "Eat a healthy diet", "Maintain healthy weight", "Exercise regularly", "Protect from sun", "Get vaccinated (HPV, HepB)", "Regular screenings"],
    treatment: ["Surgery", "Chemotherapy", "Radiation therapy", "Immunotherapy", "Targeted therapy", "Hormone therapy"],
    whenToSeeDoctor: ["Persistent unexplained symptoms", "Lumps or growths", "Unusual bleeding"],
    riskFactors: ["Age", "Family history", "Tobacco use", "Sun exposure", "Obesity", "Chronic inflammation"],
  },
  {
    name: "COPD",
    overview: "Chronic obstructive pulmonary disease (COPD) is a chronic inflammatory lung disease that causes obstructed airflow from the lungs.",
    symptoms: ["Shortness of breath", "Wheezing", "Chest tightness", "Chronic cough with mucus", "Frequent respiratory infections", "Fatigue"],
    preventions: ["Don't smoke", "Avoid secondhand smoke", "Avoid air pollutants", "Get respiratory vaccinations"],
    treatment: ["Bronchodilators", "Inhaled steroids", "Pulmonary rehabilitation", "Oxygen therapy", "Surgery in severe cases"],
    whenToSeeDoctor: ["Increased shortness of breath", "Changes in mucus", "Worsening cough"],
    riskFactors: ["Smoking", "Long-term chemical exposure", "Age", "Genetics (alpha-1 deficiency)"],
  },
  {
    name: "Arthritis",
    overview: "Arthritis is inflammation of one or more joints, causing pain and stiffness that worsen with age.",
    symptoms: ["Joint pain", "Stiffness", "Swelling", "Redness", "Decreased range of motion"],
    preventions: ["Maintain healthy weight", "Exercise regularly", "Protect joints from injury", "Don't smoke"],
    treatment: ["NSAIDs", "Disease-modifying drugs", "Physical therapy", "Joint injections", "Surgery (joint replacement)"],
    whenToSeeDoctor: ["Severe joint pain", "Sudden swelling", "Difficulty with daily activities"],
    riskFactors: ["Age", "Family history", "Previous joint injury", "Obesity", "Female gender"],
  },
  {
    name: "Kidney Disease",
    overview: "Chronic kidney disease is the gradual loss of kidney function, leading to dangerous buildup of fluids and wastes.",
    symptoms: ["Nausea", "Fatigue", "Swelling in feet/ankles", "Changes in urination", "Muscle cramps", "Itching"],
    preventions: ["Control blood pressure & diabetes", "Avoid overuse of NSAIDs", "Limit salt", "Stay hydrated", "Don't smoke"],
    treatment: ["Blood pressure medications", "Diuretics", "Dietary changes", "Dialysis", "Kidney transplant"],
    whenToSeeDoctor: ["Decreased urine output", "Severe swelling", "Persistent nausea"],
    riskFactors: ["Diabetes", "High blood pressure", "Heart disease", "Family history", "Age over 60"],
  },
  {
    name: "Liver Disease",
    overview: "Liver disease includes any condition that damages the liver and impairs its function, including hepatitis and cirrhosis.",
    symptoms: ["Yellowing of skin/eyes (jaundice)", "Abdominal pain", "Swelling in legs", "Dark urine", "Pale stool", "Chronic fatigue"],
    preventions: ["Limit alcohol", "Get hepatitis vaccines", "Practice safe sex", "Don't share needles", "Maintain healthy weight"],
    treatment: ["Medications for specific conditions", "Lifestyle changes", "Liver transplant in severe cases"],
    whenToSeeDoctor: ["Persistent abdominal pain", "Jaundice", "Confusion"],
    riskFactors: ["Heavy alcohol use", "Obesity", "Type 2 diabetes", "Hepatitis exposure", "Family history"],
  },
  {
    name: "Allergies",
    overview: "Allergies occur when your immune system reacts to a foreign substance such as pollen, food, or pet dander.",
    symptoms: ["Sneezing", "Itching", "Runny or stuffy nose", "Watery eyes", "Skin rash", "Anaphylaxis (severe)"],
    preventions: ["Avoid known allergens", "Keep windows closed during high pollen", "Use HEPA filters", "Wash hands frequently"],
    treatment: ["Antihistamines", "Nasal corticosteroids", "Decongestants", "Immunotherapy", "Epinephrine for anaphylaxis"],
    whenToSeeDoctor: ["Difficulty breathing", "Severe swelling", "Symptoms interfering with daily life"],
    riskFactors: ["Family history of allergies", "Asthma", "Childhood", "Other allergic conditions"],
  },
  {
    name: "Pneumonia",
    overview: "Pneumonia is an infection that inflames air sacs in one or both lungs, which may fill with fluid.",
    symptoms: ["Cough with phlegm", "Fever", "Chills", "Difficulty breathing", "Chest pain when breathing", "Fatigue"],
    preventions: ["Get vaccinated (pneumococcal, flu)", "Practice good hygiene", "Don't smoke", "Strengthen immune system"],
    treatment: ["Antibiotics (bacterial)", "Antivirals (viral)", "Rest and fluids", "Cough medicine", "Hospitalization if severe"],
    whenToSeeDoctor: ["Difficulty breathing", "Persistent high fever", "Chest pain", "Confusion (older adults)"],
    riskFactors: ["Age (very young or elderly)", "Smoking", "Chronic disease", "Weakened immunity"],
  },
  {
    name: "Bronchitis",
    overview: "Bronchitis is inflammation of the lining of the bronchial tubes, which carry air to and from the lungs.",
    symptoms: ["Persistent cough", "Mucus production", "Fatigue", "Shortness of breath", "Slight fever", "Chest discomfort"],
    preventions: ["Avoid smoking", "Get vaccinated", "Wash hands frequently", "Wear mask in dusty environments"],
    treatment: ["Rest and fluids", "Cough medicine", "Inhalers for chronic cases", "Antibiotics if bacterial"],
    whenToSeeDoctor: ["Cough lasting >3 weeks", "Blood in cough", "Wheezing or shortness of breath"],
    riskFactors: ["Smoking", "Air pollution", "Weak immune system", "Gastric reflux"],
  },
  {
    name: "Migraine",
    overview: "A migraine is a severe headache often accompanied by nausea, vomiting and sensitivity to light and sound.",
    symptoms: ["Throbbing head pain (often one-sided)", "Nausea", "Vomiting", "Sensitivity to light/sound", "Visual aura"],
    preventions: ["Identify and avoid triggers", "Maintain regular sleep", "Stay hydrated", "Manage stress", "Limit caffeine"],
    treatment: ["Pain relievers", "Triptans", "Anti-nausea medication", "Preventive medications", "CGRP inhibitors"],
    whenToSeeDoctor: ["Sudden severe headache", "Headache with fever or stiff neck", "Headache after head injury"],
    riskFactors: ["Family history", "Female gender", "Hormonal changes", "Stress", "Age"],
  },
  {
    name: "Obesity",
    overview: "Obesity is a complex disease involving excessive body fat that increases the risk of other diseases.",
    symptoms: ["BMI of 30 or higher", "Excess body fat", "Difficulty with physical activity", "Sleep problems"],
    preventions: ["Regular exercise", "Healthy diet", "Limit processed foods", "Monitor weight", "Adequate sleep"],
    treatment: ["Dietary changes", "Increased physical activity", "Behavior modification", "Medications", "Bariatric surgery"],
    whenToSeeDoctor: ["BMI ≥ 30", "Weight affecting daily life", "Related health issues developing"],
    riskFactors: ["Genetics", "Sedentary lifestyle", "Poor diet", "Certain medications", "Lack of sleep"],
  },
  {
    name: "Depression",
    overview: "Depression is a mood disorder causing a persistent feeling of sadness and loss of interest.",
    symptoms: ["Persistent sadness", "Loss of interest in activities", "Changes in appetite/weight", "Sleep disturbances", "Fatigue", "Feelings of worthlessness", "Thoughts of death"],
    preventions: ["Maintain social connections", "Exercise regularly", "Manage stress", "Seek help early", "Avoid alcohol/drugs"],
    treatment: ["Psychotherapy (CBT)", "Antidepressants", "Lifestyle changes", "Support groups", "Electroconvulsive therapy (severe)"],
    whenToSeeDoctor: ["Symptoms lasting >2 weeks", "Thoughts of self-harm", "Inability to function"],
    riskFactors: ["Family history", "Trauma", "Chronic illness", "Certain medications", "Substance abuse"],
  },
  {
    name: "Anxiety",
    overview: "Anxiety disorders involve intense, persistent worry about everyday situations that interferes with daily activities.",
    symptoms: ["Excessive worry", "Restlessness", "Rapid heartbeat", "Sweating", "Trembling", "Difficulty concentrating", "Sleep problems"],
    preventions: ["Practice stress management", "Exercise", "Limit caffeine/alcohol", "Get adequate sleep", "Seek therapy early"],
    treatment: ["Cognitive behavioral therapy", "Anti-anxiety medications", "SSRIs", "Relaxation techniques", "Lifestyle changes"],
    whenToSeeDoctor: ["Worry interferes with life", "Panic attacks", "Avoidance of situations", "Physical symptoms"],
    riskFactors: ["Trauma", "Stress", "Family history", "Personality factors", "Other mental health disorders"],
  },
  {
    name: "Hypertension (High Blood Pressure)",
    overview: "Hypertension is a condition where the force of blood against artery walls is consistently too high.",
    symptoms: ["Often no symptoms (silent)", "Headaches", "Shortness of breath", "Nosebleeds (severe cases)"],
    preventions: ["Limit salt intake", "Exercise regularly", "Maintain healthy weight", "Limit alcohol", "Don't smoke", "Manage stress"],
    treatment: ["ACE inhibitors", "Diuretics", "Beta blockers", "Lifestyle modifications", "DASH diet"],
    whenToSeeDoctor: ["BP consistently above 130/80", "Severe headache with high BP", "Chest pain"],
    riskFactors: ["Age", "Family history", "Obesity", "High salt intake", "Stress", "Chronic conditions"],
  },
  {
    name: "Tuberculosis",
    overview: "Tuberculosis (TB) is a potentially serious infectious bacterial disease that mainly affects the lungs.",
    symptoms: ["Persistent cough (3+ weeks)", "Coughing up blood", "Chest pain", "Fatigue", "Fever", "Night sweats", "Weight loss"],
    preventions: ["BCG vaccination", "Avoid close contact with TB patients", "Good ventilation", "Wear mask if exposed"],
    treatment: ["Multi-drug antibiotic therapy (6-9 months)", "Directly observed therapy", "Isoniazid", "Rifampin"],
    whenToSeeDoctor: ["Persistent cough", "Coughing up blood", "Unexplained weight loss with fever"],
    riskFactors: ["Weakened immune system", "HIV", "Close contact with infected", "Living in crowded conditions"],
  },
  {
    name: "Hepatitis",
    overview: "Hepatitis is inflammation of the liver, most commonly caused by viral infection (types A, B, C, D, E).",
    symptoms: ["Fatigue", "Jaundice", "Abdominal pain", "Loss of appetite", "Nausea", "Dark urine"],
    preventions: ["Vaccination (A and B)", "Safe food and water", "Practice safe sex", "Don't share needles"],
    treatment: ["Rest and supportive care", "Antiviral medications", "Liver transplant (severe)", "Interferon therapy"],
    whenToSeeDoctor: ["Jaundice", "Persistent fatigue with abdominal pain", "Possible exposure"],
    riskFactors: ["Unsafe injection practices", "Unprotected sex", "Travel to endemic areas"],
  },
  {
    name: "HIV/AIDS",
    overview: "HIV is a virus that attacks the immune system; AIDS is the advanced stage of HIV infection.",
    symptoms: ["Fever", "Fatigue", "Swollen lymph nodes", "Sore throat", "Rash", "Muscle aches", "Recurrent infections"],
    preventions: ["Safe sex practices", "PrEP medication", "Don't share needles", "Get tested regularly"],
    treatment: ["Antiretroviral therapy (ART)", "Regular monitoring", "Treatment of opportunistic infections"],
    whenToSeeDoctor: ["Possible exposure", "Persistent unexplained symptoms", "Regular screening if at-risk"],
    riskFactors: ["Unprotected sex", "Sharing needles", "Mother-to-child transmission", "Blood transfusions (rare)"],
  },
  {
    name: "Malaria",
    overview: "Malaria is a serious mosquito-borne disease caused by Plasmodium parasites.",
    symptoms: ["High fever", "Chills", "Sweating", "Headache", "Nausea", "Muscle pain", "Anemia"],
    preventions: ["Use mosquito nets", "Insect repellent", "Antimalarial medication", "Eliminate standing water"],
    treatment: ["Antimalarial drugs (artemisinin-based)", "Chloroquine", "Hospitalization for severe cases"],
    whenToSeeDoctor: ["Fever after travel to endemic area", "Severe symptoms"],
    riskFactors: ["Travel to tropical regions", "Lack of preventive measures", "Pregnancy"],
  },
  {
    name: "Dengue Fever",
    overview: "Dengue is a mosquito-borne viral infection causing flu-like illness, sometimes severe.",
    symptoms: ["High fever", "Severe headache", "Pain behind eyes", "Joint and muscle pain", "Rash", "Mild bleeding"],
    preventions: ["Eliminate mosquito breeding", "Use repellent", "Wear protective clothing", "Mosquito nets"],
    treatment: ["Rest and fluids", "Pain relievers (acetaminophen, not aspirin)", "Hospitalization for severe dengue"],
    whenToSeeDoctor: ["Severe abdominal pain", "Persistent vomiting", "Bleeding gums or nose"],
    riskFactors: ["Living/traveling in tropical areas", "Previous dengue infection"],
  },
  {
    name: "Anemia",
    overview: "Anemia is a condition in which you lack enough healthy red blood cells to carry adequate oxygen.",
    symptoms: ["Fatigue", "Weakness", "Pale skin", "Shortness of breath", "Dizziness", "Cold hands and feet"],
    preventions: ["Iron-rich diet", "Vitamin B12 and folate", "Vitamin C for iron absorption"],
    treatment: ["Iron supplements", "Vitamin supplements", "Blood transfusions (severe)", "Treat underlying cause"],
    whenToSeeDoctor: ["Persistent fatigue", "Pale skin with weakness", "Heart palpitations"],
    riskFactors: ["Poor diet", "Menstruation", "Pregnancy", "Chronic conditions", "Family history"],
  },
  {
    name: "Osteoporosis",
    overview: "Osteoporosis is a disease that weakens bones, making them fragile and more likely to break.",
    symptoms: ["Back pain", "Loss of height", "Stooped posture", "Bones that break easily"],
    preventions: ["Calcium-rich diet", "Vitamin D", "Weight-bearing exercise", "Don't smoke", "Limit alcohol"],
    treatment: ["Bisphosphonates", "Hormone therapy", "Denosumab", "Calcium and vitamin D supplements"],
    whenToSeeDoctor: ["Bone fracture from minor fall", "Postmenopausal women", "Loss of height"],
    riskFactors: ["Female gender", "Age", "Family history", "Small body frame", "Low calcium intake"],
  },
  {
    name: "Gastroenteritis",
    overview: "Gastroenteritis is intestinal infection marked by diarrhea, cramps, nausea, vomiting and sometimes fever.",
    symptoms: ["Watery diarrhea", "Abdominal cramps", "Nausea/vomiting", "Low-grade fever", "Muscle aches"],
    preventions: ["Wash hands frequently", "Safe food handling", "Drink clean water", "Vaccinate (rotavirus)"],
    treatment: ["Rehydration", "Oral rehydration solutions", "Rest", "BRAT diet", "IV fluids if severe"],
    whenToSeeDoctor: ["Signs of dehydration", "Blood in stool", "High fever", "Symptoms >3 days"],
    riskFactors: ["Children and elderly", "Weakened immunity", "Poor sanitation"],
  },
  {
    name: "Eczema (Atopic Dermatitis)",
    overview: "Eczema is a condition causing red, itchy and inflamed skin patches.",
    symptoms: ["Dry, itchy skin", "Red patches", "Small bumps", "Thickened skin", "Cracked skin"],
    preventions: ["Moisturize daily", "Identify triggers", "Use gentle soaps", "Avoid scratching", "Humidify air"],
    treatment: ["Topical corticosteroids", "Moisturizers", "Antihistamines", "Calcineurin inhibitors", "Biologics"],
    whenToSeeDoctor: ["Skin infection signs", "Symptoms affecting sleep", "Not responding to home care"],
    riskFactors: ["Family history of allergies", "Asthma", "Hay fever", "Childhood onset"],
  },
  {
    name: "Psoriasis",
    overview: "Psoriasis is a skin disease causing red, scaly patches that can be itchy and sometimes painful.",
    symptoms: ["Red patches of skin with thick scales", "Dry, cracked skin", "Itching/burning", "Thickened nails", "Joint swelling"],
    preventions: ["Manage stress", "Avoid skin injuries", "Don't smoke", "Limit alcohol", "Moisturize"],
    treatment: ["Topical treatments", "Light therapy", "Systemic medications", "Biologics"],
    whenToSeeDoctor: ["Widespread or severe rash", "Joint pain", "Embarrassment from appearance"],
    riskFactors: ["Family history", "Stress", "Smoking", "Obesity", "Viral/bacterial infections"],
  },
  {
    name: "Acid Reflux (GERD)",
    overview: "GERD is a digestive disorder where stomach acid frequently flows back into the esophagus.",
    symptoms: ["Heartburn", "Chest pain", "Difficulty swallowing", "Regurgitation", "Chronic cough", "Hoarseness"],
    preventions: ["Avoid trigger foods", "Eat smaller meals", "Don't lie down after eating", "Maintain healthy weight", "Quit smoking"],
    treatment: ["Antacids", "H2 blockers", "Proton pump inhibitors", "Lifestyle changes", "Surgery (rare)"],
    whenToSeeDoctor: ["Symptoms >2x/week", "Difficulty swallowing", "Weight loss"],
    riskFactors: ["Obesity", "Pregnancy", "Smoking", "Hiatal hernia", "Certain foods"],
  },
  {
    name: "Irritable Bowel Syndrome (IBS)",
    overview: "IBS is a common disorder affecting the large intestine, causing cramping, abdominal pain, bloating and altered bowel habits.",
    symptoms: ["Abdominal pain/cramping", "Bloating", "Gas", "Diarrhea or constipation", "Mucus in stool"],
    preventions: ["Identify trigger foods", "Manage stress", "Get regular exercise", "Adequate sleep"],
    treatment: ["Dietary changes", "Fiber supplements", "Antispasmodics", "Probiotics", "Stress management"],
    whenToSeeDoctor: ["Rectal bleeding", "Persistent abdominal pain", "Unexplained weight loss"],
    riskFactors: ["Younger age", "Female gender", "Family history", "Mental health issues"],
  },
  {
    name: "Ulcer (Peptic)",
    overview: "Peptic ulcers are open sores that develop on the stomach lining or upper small intestine.",
    symptoms: ["Burning stomach pain", "Bloating", "Heartburn", "Nausea", "Intolerance to fatty foods"],
    preventions: ["Limit NSAIDs", "Don't smoke", "Limit alcohol", "Practice good hygiene (H. pylori)"],
    treatment: ["Antibiotics (for H. pylori)", "Proton pump inhibitors", "H2 blockers", "Antacids"],
    whenToSeeDoctor: ["Vomiting blood", "Black/tarry stools", "Sharp persistent pain"],
    riskFactors: ["H. pylori infection", "NSAID use", "Smoking", "Alcohol use", "Stress"],
  },
  {
    name: "Gallstones",
    overview: "Gallstones are hardened deposits of digestive fluid that form in the gallbladder.",
    symptoms: ["Sudden upper-right abdominal pain", "Back pain between shoulder blades", "Nausea/vomiting", "Jaundice"],
    preventions: ["Healthy weight", "High-fiber diet", "Healthy fats", "Avoid rapid weight loss"],
    treatment: ["Surgery (cholecystectomy)", "Medications to dissolve stones", "ERCP"],
    whenToSeeDoctor: ["Intense abdominal pain >2 hours", "Jaundice", "High fever with chills"],
    riskFactors: ["Female gender", "Age over 40", "Obesity", "Pregnancy", "Diabetes"],
  },
  {
    name: "Urinary Tract Infection (UTI)",
    overview: "UTIs are infections in any part of the urinary system, most often the bladder and urethra.",
    symptoms: ["Strong urge to urinate", "Burning sensation when urinating", "Cloudy urine", "Pelvic pain", "Strong-smelling urine"],
    preventions: ["Drink plenty of water", "Urinate after intercourse", "Wipe front to back", "Avoid irritating products"],
    treatment: ["Antibiotics", "Pain relievers", "Increased fluid intake"],
    whenToSeeDoctor: ["Fever with UTI symptoms", "Back/side pain", "Blood in urine"],
    riskFactors: ["Female anatomy", "Sexual activity", "Menopause", "Catheter use", "Diabetes"],
  },
  {
    name: "Epilepsy",
    overview: "Epilepsy is a central nervous system disorder in which brain activity becomes abnormal, causing seizures.",
    symptoms: ["Temporary confusion", "Uncontrollable jerking movements", "Staring spells", "Loss of consciousness", "Psychic symptoms"],
    preventions: ["Wear seatbelts/helmets", "Treat infections", "Manage cardiovascular health", "Prenatal care"],
    treatment: ["Anti-seizure medications", "Vagus nerve stimulation", "Ketogenic diet", "Surgery in some cases"],
    whenToSeeDoctor: ["First seizure", "Seizure lasting >5 minutes", "Multiple seizures", "Injury during seizure"],
    riskFactors: ["Family history", "Head injuries", "Stroke", "Brain infections", "Childhood seizures"],
  },
  {
    name: "Alzheimer's Disease",
    overview: "Alzheimer's is a progressive disease that destroys memory and other important mental functions.",
    symptoms: ["Memory loss", "Difficulty completing tasks", "Confusion with time/place", "Trouble with words", "Misplacing things", "Mood changes"],
    preventions: ["Stay mentally active", "Exercise regularly", "Healthy diet", "Social engagement", "Manage cardiovascular risk"],
    treatment: ["Cholinesterase inhibitors", "Memantine", "Lifestyle interventions", "Supportive care"],
    whenToSeeDoctor: ["Persistent memory issues", "Difficulty with daily tasks", "Family concerns about memory"],
    riskFactors: ["Age", "Family history", "Down syndrome", "Head trauma", "Cardiovascular disease"],
  },
  {
    name: "Parkinson's Disease",
    overview: "Parkinson's is a progressive nervous system disorder affecting movement.",
    symptoms: ["Tremor", "Slowed movement", "Rigid muscles", "Impaired posture", "Loss of automatic movements", "Speech changes"],
    preventions: ["Regular aerobic exercise", "Caffeine consumption (some evidence)", "Avoid pesticide exposure"],
    treatment: ["Levodopa", "Dopamine agonists", "MAO B inhibitors", "Deep brain stimulation"],
    whenToSeeDoctor: ["Persistent tremor", "Difficulty with movement", "Changes in handwriting"],
    riskFactors: ["Age", "Heredity", "Male gender", "Exposure to toxins"],
  },
  {
    name: "Multiple Sclerosis",
    overview: "MS is a disease in which the immune system eats away at the protective covering of nerves.",
    symptoms: ["Numbness/weakness", "Vision problems", "Tingling", "Fatigue", "Dizziness", "Bladder issues"],
    preventions: ["Vitamin D adequacy", "Don't smoke", "Maintain healthy weight"],
    treatment: ["Disease-modifying therapies", "Corticosteroids for flares", "Physical therapy", "Symptom-specific medications"],
    whenToSeeDoctor: ["Sudden vision changes", "Numbness/weakness on one side", "Balance problems"],
    riskFactors: ["Age 20-40", "Female gender", "Family history", "Certain infections", "Vitamin D deficiency"],
  },
  {
    name: "Lupus",
    overview: "Lupus is a systemic autoimmune disease where the immune system attacks its own tissues.",
    symptoms: ["Fatigue", "Joint pain", "Butterfly rash", "Skin lesions", "Fingers turning white in cold", "Chest pain"],
    preventions: ["Avoid sun exposure", "Don't smoke", "Manage stress", "Healthy lifestyle"],
    treatment: ["NSAIDs", "Antimalarial drugs", "Corticosteroids", "Immunosuppressants", "Biologics"],
    whenToSeeDoctor: ["Unexplained rash", "Persistent joint pain", "Severe fatigue"],
    riskFactors: ["Female gender", "Age 15-45", "Family history", "Certain ethnicities"],
  },
  {
    name: "Celiac Disease",
    overview: "Celiac disease is an immune reaction to eating gluten that damages the small intestine.",
    symptoms: ["Diarrhea", "Bloating/gas", "Fatigue", "Weight loss", "Anemia", "Skin rash"],
    preventions: ["No prevention; manage with strict gluten-free diet"],
    treatment: ["Strict lifelong gluten-free diet", "Vitamin/mineral supplements", "Follow-up monitoring"],
    whenToSeeDoctor: ["Persistent digestive issues", "Family history with symptoms", "Unexplained anemia"],
    riskFactors: ["Family history", "Type 1 diabetes", "Down syndrome", "Other autoimmune disorders"],
  },
  {
    name: "Gout",
    overview: "Gout is a form of arthritis characterized by severe pain and swelling, often in the big toe.",
    symptoms: ["Intense joint pain", "Lingering discomfort", "Inflammation/redness", "Limited range of motion"],
    preventions: ["Stay hydrated", "Limit purine-rich foods", "Limit alcohol", "Maintain healthy weight"],
    treatment: ["NSAIDs", "Colchicine", "Corticosteroids", "Urate-lowering drugs"],
    whenToSeeDoctor: ["Sudden intense joint pain", "Hot or red joint", "Pain with fever"],
    riskFactors: ["Diet high in purines", "Obesity", "Medical conditions", "Family history", "Male gender"],
  },
  {
    name: "Sinusitis",
    overview: "Sinusitis is inflammation of the tissue lining the sinuses, often caused by infection.",
    symptoms: ["Facial pain/pressure", "Stuffy nose", "Thick nasal discharge", "Reduced sense of smell", "Cough"],
    preventions: ["Avoid upper respiratory infections", "Manage allergies", "Avoid smoke/pollutants", "Use humidifier"],
    treatment: ["Saline nasal sprays", "Nasal corticosteroids", "Decongestants", "Antibiotics (bacterial)"],
    whenToSeeDoctor: ["Symptoms >10 days", "High fever", "Severe headache", "Vision changes"],
    riskFactors: ["Allergies", "Nasal polyps", "Deviated septum", "Asthma"],
  },
  {
    name: "Tonsillitis",
    overview: "Tonsillitis is inflammation of the tonsils, often caused by viral or bacterial infection.",
    symptoms: ["Sore throat", "Swollen tonsils", "Difficulty swallowing", "Fever", "Bad breath", "Stiff neck"],
    preventions: ["Good hand hygiene", "Avoid sharing utensils", "Stay away from sick people"],
    treatment: ["Rest and fluids", "Throat lozenges", "Antibiotics (bacterial)", "Tonsillectomy (recurrent)"],
    whenToSeeDoctor: ["Sore throat >2 days", "Trouble breathing/swallowing", "Drooling (in children)"],
    riskFactors: ["Young age", "Exposure to germs", "Frequent infections"],
  },
  {
    name: "Conjunctivitis (Pink Eye)",
    overview: "Pink eye is inflammation or infection of the membrane lining the eyelid and eyeball.",
    symptoms: ["Redness in white of eye", "Itchiness", "Gritty feeling", "Discharge", "Tearing"],
    preventions: ["Wash hands often", "Don't share towels", "Don't touch eyes", "Clean contact lenses properly"],
    treatment: ["Antibiotic drops (bacterial)", "Antihistamines (allergic)", "Cool compresses", "Lubricating drops"],
    whenToSeeDoctor: ["Pain in the eye", "Vision changes", "Sensitivity to light", "Severe redness"],
    riskFactors: ["Exposure to infected person", "Allergies", "Contact lens use", "Eye irritants"],
  },
  {
    name: "Chickenpox",
    overview: "Chickenpox is a highly contagious viral infection causing an itchy, blister-like rash.",
    symptoms: ["Itchy rash with blisters", "Fever", "Loss of appetite", "Headache", "Tiredness"],
    preventions: ["Varicella vaccine", "Avoid contact with infected"],
    treatment: ["Calamine lotion", "Antihistamines", "Antiviral medications (severe)", "Acetaminophen for fever"],
    whenToSeeDoctor: ["Rash spreading to eyes", "Rash with high fever", "Difficulty breathing"],
    riskFactors: ["Unvaccinated children", "Weakened immune system", "Not previously infected"],
  },
  {
    name: "Measles",
    overview: "Measles is a highly contagious viral disease that can be serious or fatal in small children.",
    symptoms: ["Fever", "Dry cough", "Runny nose", "Sore throat", "Inflamed eyes", "Koplik spots", "Rash"],
    preventions: ["MMR vaccine", "Avoid contact with infected", "Travel vaccinations"],
    treatment: ["Vitamin A supplements", "Rest and fluids", "Fever reducers", "Antibiotics for complications"],
    whenToSeeDoctor: ["Suspected exposure", "Symptoms appear", "High fever with rash"],
    riskFactors: ["Unvaccinated status", "International travel", "Vitamin A deficiency"],
  },
  {
    name: "Mumps",
    overview: "Mumps is a viral infection that primarily affects saliva-producing glands near the ears.",
    symptoms: ["Swollen salivary glands", "Fever", "Headache", "Muscle aches", "Loss of appetite", "Pain while chewing"],
    preventions: ["MMR vaccine", "Avoid close contact with infected"],
    treatment: ["Rest", "Pain relievers", "Cold or warm compresses", "Soft foods"],
    whenToSeeDoctor: ["Persistent fever", "Severe abdominal pain", "Testicular pain"],
    riskFactors: ["Unvaccinated", "Age 2-12", "Weakened immunity"],
  },
  {
    name: "Sleep Apnea",
    overview: "Sleep apnea is a serious sleep disorder where breathing repeatedly stops and starts.",
    symptoms: ["Loud snoring", "Episodes of stopped breathing", "Gasping during sleep", "Morning headache", "Daytime sleepiness", "Insomnia"],
    preventions: ["Maintain healthy weight", "Regular exercise", "Avoid alcohol/sedatives", "Sleep on side", "Don't smoke"],
    treatment: ["CPAP therapy", "Oral appliances", "Surgery", "Weight loss", "Positional therapy"],
    whenToSeeDoctor: ["Loud snoring with daytime fatigue", "Observed pauses in breathing", "Excessive daytime sleepiness"],
    riskFactors: ["Excess weight", "Neck circumference", "Male gender", "Older age", "Family history"],
  },
];

export const DISEASE_LIST = DISEASES.map((d) => d.name);
